export enum Color {
  blue, 
  black, 
  green, 
  red, 
  yellow, 
  brown, 
  orange, 
  pink, 
  purple, 
  violet, 
  white,
  gray,
  cyan,
  aliceblue,
  antiquewhite,
  aqua,
  aquamarine,
  burlywood,
  cadetblue,
  chartreuse,
  coral,
  chocolate,
  cornflowerblue,
  crimson,
  darkblue,
  darkgreen,
  darkorange,
  deeppink,
  darkviolet,
  greenyellow,
  gold,
  ivory,
  lavender,
  lime,
  limegreen,
  navy,
  olive,
  orchid,
  rebeccapurple,
  sienna,
  seagreen,
  salmon,
  sandybrown,
  skyblue,
  silver,
  snow,
  steelblue,
  tomato,
  thistle,
  turquoise
}

export const EMOJIS: string[] = [
  '😃', '😁', '😉', '😍', '😜', '😏', '😌', '😰', '👻',
  '❤', '👀', '🐱', '🐶', '🐴', '🐷', '🐫', '🐘', '🐭',
  '🐻', '🐨', '🐼', '🐧', '🐤', '🐔', '🐸', '🐢', '🐳',
  '🐬', '🐟', '🐠', '🐙', '🐚', '🐌', '🐛', '✈', '🚀',
  '⛵', '🚢', '🚲', '🚚', '🚗', '🚜', '🏍', '🏎', '🚒',
  '🚑', '🚓', '🚌', '🚃', '🍼', '☕', '🍵', '🦀', '🐞',
  '🐝', '🐜', '🐡', '🦧', '🐊', '🦉', '🦩', '🐦', '🦅',
  '🦢', '🐔', '🦃', '🐓', '🦘', '🦡', '🦛', '🐹', '🐰',
  '🐑', '🦒', '🐄', '🦁', '🐯', '🐺', '🦊', '🦍', '🐵'
]
